# Generated by Django 5.2.1 on 2025-05-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('maker', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('image', models.URLField()),
                ('link', models.URLField()),
                ('lprice', models.CharField(max_length=20)),
                ('hprice', models.CharField(blank=True, max_length=20)),
                ('mallName', models.CharField(max_length=255)),
                ('productId', models.CharField(max_length=50, unique=True)),
                ('productType', models.CharField(max_length=10)),
                ('category1', models.CharField(blank=True, max_length=100)),
                ('category2', models.CharField(blank=True, max_length=100)),
                ('category3', models.CharField(blank=True, max_length=100)),
                ('category4', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
